### ISSUE TITLE
NoClassDefFoundError Exception with jettison 1.5.3

### ISSUE THREAD

**Issue by sharma070289** [jettison-json/jettison#71]
Hi Team,

I upgraded my application from Jettision 1.2 to 1.5.3 and now strangely i am seeing the error
"NoClassDefFoundError org/codehaus/jettison/json/JSONException"

i am importing org.codehaus.jettison.json.JSONException;

however instead of JSONException if i use generic exception my application is working fine
but if i use JSONException then i am facing NoClassDefFoundError

Issue seen after upgrading to 1.5.3
